language: c

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.html)|^(LICENSE)|^(docs)'
      then
        echo "Only docs were updated, not running the CI."
        exit 0
      fi

services:
  - docker

script:
  - make

